spring:
  application:
    name: GenixBot
  main:
    lazy-initialization: true
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
jda:
  token: ${BOT_TOKEN}
twitch:
  client_id: ${TWITCH_CLIENT_ID}
  client_secret: ${TWITCH_CLIENT_SECRET}